# Generated by Django 5.0.1 on 2024-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conutry', models.CharField(max_length=50)),
                ('store', models.CharField(max_length=20)),
                ('product_list', models.JSONField()),
                ('date', models.DateTimeField()),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipt_images/')),
            ],
        ),
    ]
