# Generated by Django 5.0.1 on 2024-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='conutry',
            new_name='country',
        ),
    ]
