# Generated by Django 5.0.1 on 2024-01-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_receipt', '0002_rename_conutry_receipt_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipt_images/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_image',
        ),
    ]
