# Generated by Django 5.0.1 on 2024-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upload_delete_receiptimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='scan_mode',
            field=models.CharField(default='receipt', max_length=20),
            preserve_default=False,
        ),
    ]
