# Generated by Django 5.0.1 on 2024-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_upload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('store', models.CharField(max_length=20)),
                ('match_name', models.CharField(max_length=100)),
                ('match_certainty', models.FloatField()),
                ('nutriments', models.JSONField()),
            ],
        ),
    ]
