# Generated by Django 5.0.1 on 2024-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('unsaturated_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('complex_carbohydrates', models.FloatField()),
                ('simple_carbohydrates', models.FloatField()),
                ('protein', models.FloatField()),
                ('sodium', models.FloatField()),
                ('chloride', models.FloatField()),
                ('potassium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('sulfur', models.FloatField()),
                ('iron', models.FloatField()),
                ('zinc', models.FloatField()),
                ('iodine', models.FloatField()),
                ('selenium', models.FloatField()),
                ('copper', models.FloatField()),
                ('manganese', models.FloatField()),
                ('fluoride', models.FloatField()),
                ('chromium', models.FloatField()),
                ('molybdenum', models.FloatField()),
                ('vitamin_a', models.FloatField()),
                ('vitamin_d', models.FloatField()),
                ('vitamin_e', models.FloatField()),
                ('vitamin_k', models.FloatField()),
                ('vitamin_c', models.FloatField()),
                ('vitamin_b1', models.FloatField()),
                ('vitamin_b2', models.FloatField()),
                ('vitamin_b3', models.FloatField()),
                ('vitamin_b5', models.FloatField()),
                ('vitamin_b6', models.FloatField()),
                ('vitamin_b7', models.FloatField()),
                ('vitamin_b9', models.FloatField()),
                ('vitamin_b12', models.FloatField()),
            ],
        ),
    ]
