# Generated by Django 5.0.1 on 2024-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
    ]
